# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [8]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the tutorial. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.



##DataTypes in NumPy 

##Data type	Description  
bool_ 	Boolean (True or False) stored as a byte  
int_ 	Default integer type (same as C long; normally either int64 or int32)  
intc	Identical to C int (normally int32 or int64)  
intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)  
int8	Byte (-128 to 127)  
int16	Integer (-32768 to 32767)  
int32	Integer (-2147483648 to 2147483647)  
int64	Integer (-9223372036854775808 to 9223372036854775807)  
uint8	Unsigned integer (0 to 255)  
uint16	Unsigned integer (0 to 65535)  
uint32	Unsigned integer (0 to 4294967295)  
uint64	Unsigned integer (0 to 18446744073709551615)  
float_	Shorthand for float64.  
float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa  
float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa  
float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa  
complex_	Shorthand for complex128.  
complex64	Complex number, represented by two 32-bit floats (real and imaginary components)  
complex128	Complex number, represented by two 64-bit floats (real and imaginary components)  


## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [9]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [10]:
np.array(my_list)

array([1, 2, 3])

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##  From DataType Function

In [14]:
x = np.float32(2.0)
x

2.0

In [15]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones(3)

array([ 1.,  1.,  1.])

In [28]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [21]:
np.linspace(0,10,2)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Indices

indices() will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension.

In [26]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

## eye

Creates an identity matrix

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [28]:
np.random.rand(4)

array([0.4587286 , 0.96588544, 0.10740889, 0.77863234])

In [29]:
np.random.rand(10,10)

array([[0.6976106 , 0.41932965, 0.14039241, 0.90309411, 0.81657652,
        0.71877335, 0.43549561, 0.10516286, 0.35898684, 0.71244299],
       [0.30790415, 0.51655508, 0.50350844, 0.50959042, 0.06853998,
        0.12199818, 0.97138769, 0.17686907, 0.35651362, 0.6895614 ],
       [0.7555199 , 0.02572359, 0.25601503, 0.25406778, 0.92070529,
        0.25409593, 0.58908417, 0.64514064, 0.14866416, 0.705098  ],
       [0.60185692, 0.2329027 , 0.50175892, 0.83794413, 0.55362558,
        0.11230468, 0.79147465, 0.38960812, 0.88916344, 0.85117356],
       [0.53713119, 0.32622462, 0.0171255 , 0.5614007 , 0.04541553,
        0.89394188, 0.13892792, 0.52454015, 0.90439801, 0.21268873],
       [0.7304837 , 0.58495536, 0.24562122, 0.88264546, 0.16145902,
        0.02947316, 0.89537064, 0.3185859 , 0.74274134, 0.93828306],
       [0.49279034, 0.87604758, 0.27748554, 0.10111209, 0.03812939,
        0.39514829, 0.48870566, 0.04834861, 0.64850435, 0.74415013],
       [0.02803113, 0.99464117, 0.7760611

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [30]:
np.random.randn(2)

array([0.72798222, 0.17433623])

In [31]:
np.random.randn(5,5)

array([[ 0.08751159, -1.26944309, -0.91119357, -0.69257563, -1.09872192],
       [-1.79943685,  1.14596923,  0.41742229,  0.3599024 , -0.9431968 ],
       [ 0.39975128, -0.69862105, -0.62681132,  1.48004886, -0.89108723],
       [ 0.18223903, -0.01140161,  0.53894401,  0.93519631,  1.90545052],
       [ 1.40489509,  0.71276544,  0.59506825, -1.16556675, -0.54246857]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [34]:
np.random.randint(1,100)

19

In [36]:
np.random.randint(1,100,20)

array([17, 44, 44, 85, 78, 88, 94, 73, 26, 95,  9, 33, 67, 19, 89, 65, 14,
       81, 80,  1])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [38]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr

array([13, 11, 42, 32, 31, 42, 46, 14, 47,  4])

## Reshape
Returns an array containing the same data with a new shape.

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax



In [48]:
ranarr

array([13, 11, 42, 32, 31, 42, 46, 14, 47,  4])

In [49]:
ranarr.max()

47

In [50]:
ranarr.argmax()

8

In [51]:
ranarr.min()

4

In [52]:
ranarr.argmin()

9

## Shape

Shape is an attribute that arrays have (not a method):

In [42]:
# Vector
arr.shape

(25,)

In [43]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [44]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [46]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [47]:
arr.dtype

dtype('int64')

# Great Job!